// File : pkg/database/database_user.go
// Deskripsi : Fungsi untuk export user grants dari database
// Author : Hadiyatna Muflihun
// Tanggal : 2024-11-18
// Last Modified : 2024-11-18

package database

import (
	"context"
	"fmt"
	"strings"
)

// GetUserList mengambil daftar user dari mysql.user table
func (c *Client) GetUserList(ctx context.Context) ([]UserInfo, error) {
	query := `SELECT user, host FROM mysql.user WHERE user != ''`

	rows, err := c.db.QueryContext(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("gagal mendapatkan daftar user: %w", err)
	}
	defer rows.Close()

	var users []UserInfo
	for rows.Next() {
		var user, host string
		if err := rows.Scan(&user, &host); err != nil {
			return nil, fmt.Errorf("gagal scan user: %w", err)
		}
		users = append(users, UserInfo{
			User: user,
			Host: host,
		})
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterasi rows: %w", err)
	}

	return users, nil
}

// GetUserGrants mengambil SHOW GRANTS untuk setiap user
func (c *Client) GetUserGrants(ctx context.Context, user, host string) ([]string, error) {
	query := fmt.Sprintf("SHOW GRANTS FOR '%s'@'%s'", user, host)

	rows, err := c.db.QueryContext(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("gagal mendapatkan grants untuk %s@%s: %w", user, host, err)
	}
	defer rows.Close()

	var grants []string
	for rows.Next() {
		var grant string
		if err := rows.Scan(&grant); err != nil {
			return nil, fmt.Errorf("gagal scan grant: %w", err)
		}
		// Tambahkan semicolon jika belum ada
		if !strings.HasSuffix(grant, ";") {
			grant += ";"
		}
		grants = append(grants, grant)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterasi grants: %w", err)
	}

	return grants, nil
}

// ExportAllUserGrants mengambil semua user grants dan mengembalikan dalam format SQL
func (c *Client) ExportAllUserGrants(ctx context.Context) (string, error) {
	// Dapatkan daftar user
	users, err := c.GetUserList(ctx)
	if err != nil {
		return "", err
	}

	if len(users) == 0 {
		return "", fmt.Errorf("tidak ada user yang ditemukan")
	}

	var builder strings.Builder
	builder.WriteString("-- User Grants Export\n")
	builder.WriteString(fmt.Sprintf("-- Total users: %d\n", len(users)))
	builder.WriteString("-- Generated by sfDBTools\n\n")

	// Untuk setiap user, ambil grants-nya
	for _, userInfo := range users {
		grants, err := c.GetUserGrants(ctx, userInfo.User, userInfo.Host)
		if err != nil {
			// Log warning tapi lanjutkan ke user berikutnya
			builder.WriteString(fmt.Sprintf("-- Warning: Failed to get grants for '%s'@'%s': %v\n",
				userInfo.User, userInfo.Host, err))
			continue
		}

		builder.WriteString(fmt.Sprintf("\n-- Grants for '%s'@'%s'\n", userInfo.User, userInfo.Host))
		for _, grant := range grants {
			builder.WriteString(grant)
			builder.WriteString("\n")
		}
	}

	// Tambahkan FLUSH PRIVILEGES di akhir
	builder.WriteString("\nFLUSH PRIVILEGES;\n")

	return builder.String(), nil
}

// UserInfo menyimpan informasi user dari mysql.user
type UserInfo struct {
	User string
	Host string
}
