package metadata

import (
	"context"
	"fmt"
	"strings"

	"sfDBTools/pkg/database"
)

// UserInfo menyimpan informasi user dari mysql.user.
type UserInfo struct {
	User string
	Host string
}

// GetUserList mengambil daftar user dari mysql.user table.
func GetUserList(ctx context.Context, client *database.Client) ([]UserInfo, error) {
	query := `SELECT user, host FROM mysql.user WHERE user != ''`

	rows, err := client.DB().QueryContext(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("gagal mendapatkan daftar user: %w", err)
	}
	defer rows.Close()

	users := make([]UserInfo, 0)
	for rows.Next() {
		var user, host string
		if err := rows.Scan(&user, &host); err != nil {
			return nil, fmt.Errorf("gagal scan user: %w", err)
		}
		users = append(users, UserInfo{User: user, Host: host})
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterasi rows: %w", err)
	}

	return users, nil
}

// GetUserGrants mengambil SHOW GRANTS untuk setiap user.
func GetUserGrants(ctx context.Context, client *database.Client, user, host string) ([]string, error) {
	query := fmt.Sprintf("SHOW GRANTS FOR '%s'@'%s'", user, host)

	rows, err := client.DB().QueryContext(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("gagal mendapatkan grants untuk %s@%s: %w", user, host, err)
	}
	defer rows.Close()

	grants := make([]string, 0)
	for rows.Next() {
		var grant string
		if err := rows.Scan(&grant); err != nil {
			return nil, fmt.Errorf("gagal scan grant: %w", err)
		}
		if !strings.HasSuffix(grant, ";") {
			grant += ";"
		}
		grants = append(grants, grant)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterasi grants: %w", err)
	}

	return grants, nil
}

// ExportAllUserGrants mengambil semua user grants dan mengembalikan dalam format SQL.
func ExportAllUserGrants(ctx context.Context, client *database.Client) (string, error) {
	users, err := GetUserList(ctx, client)
	if err != nil {
		return "", err
	}

	if len(users) == 0 {
		return "", fmt.Errorf("tidak ada user yang ditemukan")
	}

	var builder strings.Builder
	builder.WriteString("-- User Grants Export\n")
	builder.WriteString(fmt.Sprintf("-- Total users: %d\n", len(users)))
	builder.WriteString("-- Generated by sfDBTools\n\n")

	for _, userInfo := range users {
		grants, err := GetUserGrants(ctx, client, userInfo.User, userInfo.Host)
		if err != nil {
			builder.WriteString(fmt.Sprintf("-- Warning: Failed to get grants for '%s'@'%s': %v\n", userInfo.User, userInfo.Host, err))
			continue
		}

		builder.WriteString(fmt.Sprintf("\n-- Grants for '%s'@'%s'\n", userInfo.User, userInfo.Host))
		for _, grant := range grants {
			builder.WriteString(grant)
			builder.WriteString("\n")
		}
	}

	builder.WriteString("\nFLUSH PRIVILEGES;\n")
	return builder.String(), nil
}

// ExportUserGrantsForDatabases mengambil user grants hanya untuk user yang memiliki akses ke database tertentu.
func ExportUserGrantsForDatabases(ctx context.Context, client *database.Client, databases []string) (string, error) {
	if len(databases) == 0 {
		return "", fmt.Errorf("daftar database kosong")
	}

	allUsers, err := GetUserList(ctx, client)
	if err != nil {
		return "", err
	}
	if len(allUsers) == 0 {
		return "", fmt.Errorf("tidak ada user yang ditemukan")
	}

	var builder strings.Builder
	builder.WriteString("-- User Grants Export (Filtered by Databases)\n")
	builder.WriteString(fmt.Sprintf("-- Databases: %s\n", strings.Join(databases, ", ")))
	builder.WriteString("-- Generated by sfDBTools\n\n")

	totalUsersWithGrants := 0

	for _, userInfo := range allUsers {
		allGrants, err := GetUserGrants(ctx, client, userInfo.User, userInfo.Host)
		if err != nil {
			builder.WriteString(fmt.Sprintf("-- Warning: Failed to get grants for '%s'@'%s': %v\n", userInfo.User, userInfo.Host, err))
			continue
		}

		var usageGrant string
		relevantGrants := make([]string, 0)

		for _, grant := range allGrants {
			grantUpper := strings.ToUpper(grant)
			if strings.Contains(grantUpper, "GRANT USAGE ON") {
				usageGrant = grant
				continue
			}

			isRelevant := false
			for _, dbName := range databases {
				dbNameUpper := strings.ToUpper(dbName)
				if strings.Contains(grantUpper, fmt.Sprintf(" ON `%s`.* ", dbNameUpper)) ||
					(strings.Contains(grantUpper, fmt.Sprintf(" ON `%s`.*", dbNameUpper)) && strings.Contains(grantUpper, " TO ")) {
					isRelevant = true
					break
				}
				if strings.Contains(grantUpper, fmt.Sprintf(" ON %s.* TO ", dbNameUpper)) {
					isRelevant = true
					break
				}
			}

			if isRelevant {
				relevantGrants = append(relevantGrants, grant)
			}
		}

		if len(relevantGrants) > 0 {
			builder.WriteString(fmt.Sprintf("\n-- Grants for '%s'@'%s'\n", userInfo.User, userInfo.Host))
			if usageGrant != "" {
				builder.WriteString(usageGrant)
				builder.WriteString("\n")
			}
			for _, grant := range relevantGrants {
				builder.WriteString(grant)
				builder.WriteString("\n")
			}
			totalUsersWithGrants++
		}
	}

	if totalUsersWithGrants == 0 {
		return "", fmt.Errorf("tidak ada user dengan grants ke database yang ditentukan")
	}

	builder.WriteString("\nFLUSH PRIVILEGES;\n")
	return builder.String(), nil
}
