// File : internal/backup/helpers/user_grants_export.go
// Deskripsi : Export all user grants (full export untuk backup mode 'all')
// Author : Hadiyatna Muflihun
// Tanggal : 22 Desember 2024
// Last Modified : 22 Desember 2024
// Moved from: pkg/database/database_user_export.go

package helpers

import (
	"context"
	"fmt"
	"sfDBTools/pkg/database"
	"strings"
)

// ExportAllUserGrants mengambil semua user grants dan mengembalikan dalam format SQL
func ExportAllUserGrants(ctx context.Context, client *database.Client) (string, error) {
	// Dapatkan daftar user
	users, err := GetUserList(ctx, client)
	if err != nil {
		return "", err
	}

	if len(users) == 0 {
		return "", fmt.Errorf("tidak ada user yang ditemukan")
	}

	var builder strings.Builder
	builder.WriteString("-- User Grants Export\n")
	builder.WriteString(fmt.Sprintf("-- Total users: %d\n", len(users)))
	builder.WriteString("-- Generated by sfDBTools\n\n")

	// Untuk setiap user, ambil grants-nya
	for _, userInfo := range users {
		grants, err := GetUserGrants(ctx, client, userInfo.User, userInfo.Host)
		if err != nil {
			// Log warning tapi lanjutkan ke user berikutnya
			builder.WriteString(fmt.Sprintf("-- Warning: Failed to get grants for '%s'@'%s': %v\n",
				userInfo.User, userInfo.Host, err))
			continue
		}

		builder.WriteString(fmt.Sprintf("\n-- Grants for '%s'@'%s'\n", userInfo.User, userInfo.Host))
		for _, grant := range grants {
			builder.WriteString(grant)
			builder.WriteString("\n")
		}
	}

	// Tambahkan FLUSH PRIVILEGES di akhir
	builder.WriteString("\nFLUSH PRIVILEGES;\n")

	return builder.String(), nil
}
