// File : internal/backup/helpers/user_grants_filter.go
// Deskripsi : Export filtered user grants (untuk mode filter/primary/secondary)
// Author : Hadiyatna Muflihun
// Tanggal : 22 Desember 2024
// Last Modified : 22 Desember 2024
// Moved from: pkg/database/database_user_filter.go

package helpers

import (
	"context"
	"fmt"
	"sfDBTools/pkg/database"
	"strings"
)

// ExportUserGrantsForDatabases mengambil user grants hanya untuk user yang memiliki akses ke database tertentu
func ExportUserGrantsForDatabases(ctx context.Context, client *database.Client, databases []string) (string, error) {
	if len(databases) == 0 {
		return "", fmt.Errorf("daftar database kosong")
	}

	// Dapatkan daftar user
	allUsers, err := GetUserList(ctx, client)
	if err != nil {
		return "", err
	}

	if len(allUsers) == 0 {
		return "", fmt.Errorf("tidak ada user yang ditemukan")
	}

	var builder strings.Builder
	builder.WriteString("-- User Grants Export (Filtered by Databases)\n")
	builder.WriteString(fmt.Sprintf("-- Databases: %s\n", strings.Join(databases, ", ")))
	builder.WriteString("-- Generated by sfDBTools\n\n")

	totalUsersWithGrants := 0

	// Untuk setiap user, cek dulu apakah punya grant ke database target
	for _, userInfo := range allUsers {
		allGrants, err := GetUserGrants(ctx, client, userInfo.User, userInfo.Host)
		if err != nil {
			builder.WriteString(fmt.Sprintf("-- Warning: Failed to get grants for '%s'@'%s': %v\n",
				userInfo.User, userInfo.Host, err))
			continue
		}

		// Filter hanya grants yang relevan dengan database yang ditentukan
		// Pisahkan GRANT USAGE dan grants lainnya
		var usageGrant string
		var relevantGrants []string

		for _, grant := range allGrants {
			grantUpper := strings.ToUpper(grant)

			// Simpan GRANT USAGE untuk digunakan nanti
			if strings.Contains(grantUpper, "GRANT USAGE ON") {
				usageGrant = grant
				continue
			}

			// Check apakah grant ini untuk salah satu database yang ditentukan
			isRelevant := false
			for _, dbName := range databases {
				dbNameUpper := strings.ToUpper(dbName)

				// Pattern matching untuk berbagai format grant - exact match:
				// Dengan backtick: ON `database`.*
				if strings.Contains(grantUpper, fmt.Sprintf(" ON `%s`.* ", dbNameUpper)) ||
					strings.Contains(grantUpper, fmt.Sprintf(" ON `%s`.*", dbNameUpper)) && strings.Contains(grantUpper, " TO ") {
					isRelevant = true
					break
				}

				// Tanpa backtick: ON database.* (dengan word boundary check)
				if strings.Contains(grantUpper, fmt.Sprintf(" ON %s.* TO ", dbNameUpper)) {
					isRelevant = true
					break
				}
			}

			if isRelevant {
				relevantGrants = append(relevantGrants, grant)
			}
		}

		// Hanya tampilkan user yang memiliki setidaknya satu grant relevan
		if len(relevantGrants) > 0 {
			builder.WriteString(fmt.Sprintf("\n-- Grants for '%s'@'%s'\n", userInfo.User, userInfo.Host))

			// Tampilkan GRANT USAGE dulu (jika ada)
			if usageGrant != "" {
				builder.WriteString(usageGrant)
				builder.WriteString("\n")
			}

			// Kemudian grants ke database spesifik
			for _, grant := range relevantGrants {
				builder.WriteString(grant)
				builder.WriteString("\n")
			}
			totalUsersWithGrants++
		}
	}

	if totalUsersWithGrants == 0 {
		return "", fmt.Errorf("tidak ada user dengan grants ke database yang ditentukan")
	}

	// Tambahkan FLUSH PRIVILEGES di akhir
	builder.WriteString("\nFLUSH PRIVILEGES;\n")

	return builder.String(), nil
}
