package usersgrants

import (
	"context"
	"database/sql"
	"fmt"
	"sfdbtools/internal/shared/database"
	"strings"
)

func getUserGrants(ctx context.Context, client *database.Client, user, host string) ([]string, error) {
	query := fmt.Sprintf("SHOW GRANTS FOR %s", quoteMySQLAccount(user, host))

	rows, err := client.DB().QueryContext(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("gagal mendapatkan grants untuk %s@%s: %w", user, host, err)
	}
	defer rows.Close()

	grants := make([]string, 0, 16)
	for rows.Next() {
		var grant string
		if err := rows.Scan(&grant); err != nil {
			return nil, fmt.Errorf("gagal scan grant: %w", err)
		}
		grants = append(grants, ensureSemicolon(grant))
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterasi grants: %w", err)
	}
	return grants, nil
}

func tryGetCreateUser(ctx context.Context, client *database.Client, user, host string) (stmt string, ok bool, warn error) {
	query := fmt.Sprintf("SHOW CREATE USER %s", quoteMySQLAccount(user, host))
	rows, err := client.DB().QueryContext(ctx, query)
	if err != nil {
		return "", false, err
	}
	defer rows.Close()
	if !rows.Next() {
		return "", false, fmt.Errorf("SHOW CREATE USER: tidak ada row")
	}

	cols, _ := rows.Columns()
	if len(cols) == 0 {
		return "", false, fmt.Errorf("SHOW CREATE USER: tidak ada kolom")
	}
	raw := make([]sql.RawBytes, len(cols))
	args := make([]any, len(cols))
	for i := range raw {
		args[i] = &raw[i]
	}
	if err := rows.Scan(args...); err != nil {
		return "", false, err
	}

	// Cari kolom pertama yang berisi string "CREATE USER ..."
	for i := 0; i < len(raw); i++ {
		s := strings.TrimSpace(string(raw[i]))
		if s == "" {
			continue
		}
		upper := strings.ToUpper(s)
		if strings.Contains(upper, "CREATE USER") {
			return ensureSemicolon(makeCreateUserIdempotent(s)), true, nil
		}
	}

	// Fallback: pakai kolom pertama jika non-empty
	s0 := strings.TrimSpace(string(raw[0]))
	if s0 == "" {
		return "", false, fmt.Errorf("SHOW CREATE USER: output kosong")
	}
	return ensureSemicolon(makeCreateUserIdempotent(s0)), true, nil
}

func makeCreateUserIdempotent(stmt string) string {
	s := strings.TrimSpace(stmt)
	if s == "" {
		return ""
	}
	u := strings.ToUpper(s)
	if strings.HasPrefix(u, "CREATE USER IF NOT EXISTS ") {
		return s
	}
	if strings.HasPrefix(u, "CREATE USER ") {
		// Insert IF NOT EXISTS right after CREATE USER
		return "CREATE USER IF NOT EXISTS " + strings.TrimSpace(s[len("CREATE USER "):])
	}
	return s
}

func hasRelevantGrant(grants []string, databases []string) (usageGrant string, relevant []string) {
	if len(databases) == 0 {
		return "", grants
	}

	relevant = make([]string, 0, len(grants))
	for _, g := range grants {
		up := strings.ToUpper(g)
		if strings.Contains(up, "GRANT USAGE ON") {
			usageGrant = g
			continue
		}

		for _, db := range databases {
			for _, needle := range databasesNeedlePatterns(db) {
				if strings.Contains(up, needle) {
					relevant = append(relevant, g)
					goto NextGrant
				}
			}
		}
	NextGrant:
	}
	return usageGrant, relevant
}

// ExportSQL meng-export user accounts dan grants menjadi SQL.
// Ini best-effort: jika gagal ambil grants / create-user untuk satu user, proses lanjut ke user berikutnya.
func ExportSQL(ctx context.Context, client *database.Client, opts ExportOptions) (string, ExportStats, error) {
	if client == nil {
		return "", ExportStats{}, fmt.Errorf("client nil")
	}
	if !opts.IncludeCreateUser && !opts.IncludeGrants {
		return "", ExportStats{}, fmt.Errorf("tidak ada yang diexport: include-create-user dan include-grants keduanya false")
	}

	accounts, err := ResolveUserAccounts(ctx, client, opts)
	if err != nil {
		return "", ExportStats{}, err
	}
	if len(accounts) == 0 {
		return "", ExportStats{}, fmt.Errorf("tidak ada user ditemukan")
	}

	sysSpecs := make([]systemUserSpec, 0, len(opts.SystemUsers))
	for _, s := range opts.SystemUsers {
		if sp, ok := parseSystemUserSpec(s); ok {
			sysSpecs = append(sysSpecs, sp)
		}
	}

	var b strings.Builder
	b.WriteString("-- User Grants Export\n")
	b.WriteString("-- Generated by sfdbtools\n\n")

	stats := ExportStats{TotalUsersInput: len(accounts)}
	for _, acc := range accounts {
		if opts.ExcludeSystemUsers && isSystemUser(acc, sysSpecs) {
			stats.TotalUsersSkipped++
			continue
		}

		// Ambil grants jika dibutuhkan:
		// - untuk export grants
		// - untuk menentukan relevansi saat filter database diaktifkan
		var usage string
		var relevant []string
		needsGrants := opts.IncludeGrants || len(opts.Databases) > 0
		if needsGrants {
			grants, gerr := getUserGrants(ctx, client, acc.User, acc.Host)
			if gerr != nil {
				stats.Warnings++
				b.WriteString(fmt.Sprintf("\n-- Warning: Failed to get grants for '%s'@'%s': %v\n", acc.User, acc.Host, gerr))
				// Jika sedang mode filtered (Databases diisi), kita tidak bisa menentukan relevansi; skip user ini.
				if len(opts.Databases) > 0 {
					stats.TotalUsersSkipped++
				}
				continue
			}
			usage, relevant = hasRelevantGrant(grants, opts.Databases)
			if len(opts.Databases) > 0 && len(relevant) == 0 {
				stats.TotalUsersSkipped++
				continue
			}
		}

		// Pada titik ini user dianggap relevan (atau tidak ada filter).
		stats.TotalUsersWritten++

		if opts.IncludeCreateUser {
			if stmt, ok, warn := tryGetCreateUser(ctx, client, acc.User, acc.Host); ok {
				b.WriteString(fmt.Sprintf("\n-- Create user '%s'@'%s'\n", acc.User, acc.Host))
				b.WriteString(stmt)
				b.WriteString("\n")
			} else {
				stats.Warnings++
				b.WriteString(fmt.Sprintf("\n-- Warning: Failed to get CREATE USER for '%s'@'%s': %v\n", acc.User, acc.Host, warn))
				b.WriteString(fmt.Sprintf("CREATE USER IF NOT EXISTS %s;\n", quoteMySQLAccount(acc.User, acc.Host)))
			}
		}

		if opts.IncludeGrants {
			b.WriteString(fmt.Sprintf("\n-- Grants for '%s'@'%s'\n", acc.User, acc.Host))
			if usage != "" {
				b.WriteString(usage)
				b.WriteString("\n")
				stats.TotalGrantLines++
			}
			for _, g := range relevant {
				b.WriteString(g)
				b.WriteString("\n")
				stats.TotalGrantLines++
			}
		}
	}

	if opts.FlushPrivileges {
		b.WriteString("\nFLUSH PRIVILEGES;\n")
	}

	// Compatibility behavior: jika mode filtered (Databases diisi) tapi tidak ada grant yang relevan,
	// kembalikan error agar caller bisa decide skip (non-fatal).
	if len(opts.Databases) > 0 && stats.TotalUsersWritten == 0 {
		// Bungkus sebagai sentinel error agar caller tidak perlu string-match.
		return "", stats, fmt.Errorf("%w", ErrNoUserWithGrants)
	}

	return b.String(), stats, nil
}
