package consts

const (
	// Database Connection
	ENV_DB_HOST        = "SFDB_DB_HOST"
	ENV_DB_PORT        = "SFDB_DB_PORT"
	ENV_DB_USER        = "SFDB_DB_USER"
	ENV_DB_PASSWORD    = "SFDB_DB_PASSWORD"
	ENV_DB_NAME        = "SFDB_DB_NAME"
	ENV_SOURCE_DB_NAME = "SFDB_SOURCE_DB_NAME"
	ENV_DEST_DB_NAME   = "SFDB_DEST_DB_NAME"
	ENV_APP_DB_NAME    = "SFDB_APP_DB_NAME"

	// Encryption Key
	ENV_SOURCE_PROFILE_KEY = "SFDB_SOURCE_PROFILE_KEY"
	ENV_TARGET_PROFILE_KEY = "SFDB_TARGET_PROFILE_KEY"

	// Other constants can be added here as needed

	ENV_TARGET_DB_HOST     = "SFDB_TARGET_DB_HOST"
	ENV_TARGET_DB_PORT     = "SFDB_TARGET_DB_PORT"
	ENV_TARGET_DB_USER     = "SFDB_TARGET_DB_USER"
	ENV_TARGET_DB_PASSWORD = "SFDB_TARGET_DB_PASSWORD"

	ENV_SOURCE_DB_HOST     = "SFDB_SOURCE_DB_HOST"
	ENV_SOURCE_DB_PORT     = "SFDB_SOURCE_DB_PORT"
	ENV_SOURCE_DB_USER     = "SFDB_SOURCE_DB_USER"
	ENV_SOURCE_DB_PASSWORD = "SFDB_SOURCE_DB_PASSWORD"

	ENV_SOURCE_PROFILE = "SFDB_SOURCE_PROFILE"
	ENV_TARGET_PROFILE = "SFDB_TARGET_PROFILE"

	ENV_DAEMON_MODE = "SFDB_DAEMON_MODE"
)
